version: "3.5"

services:

  notebooks:
    build: notebooks
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./notebooks:/mnt/code
      - ./src/python/pkg_name:/mnt/code/pkg_name
      - ./data:/mnt/data/
    ports:
      - 8888:8888
