name: experiment2_project_&_labels
# Controls when the action will run. Triggers the workflow on creation of a new project
on:
  push:
    branches: [ develop, main ]
jobs:

  create-labels:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Copy a label
      - name: Copy a label
        run: gh label create 
              'blocked2 🚧'
              description="Task blocked by some other issue."
              color='E7A922'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
