
name: experiment

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
  push:
    branches: [ develop, main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  create-labels:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Copy a label
      - name: Copy a label
        run: gh labels
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
